import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './StoreProvider';
import StyledComponentsRegistry from '@/lib/styleRegistry/AntdStyledRegistry';
import ThemeProvider from '@/utils/theme/themeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider>
                    <ThemeProvider>
                        <StyledComponentsRegistry>
                            {children}
                        </StyledComponentsRegistry>
                    </ThemeProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
